
#shell
shell /bin/zsh

mouse_hide_wait 0.0

map ctrl+shift+up        scroll_line_up
map ctrl+shift+down      scroll_line_down
map ctrl+shift+k         scroll_line_up
map ctrl+shift+j         scroll_line_down
map ctrl+shift+page_up   scroll_page_up
map ctrl+shift+page_down scroll_page_down
map ctrl+shift+home      scroll_home
map ctrl+shift+end       scroll_end


map ctrl+shift+enter    new_window
map ctrl+shift+]        next_window
map ctrl+shift+[        previous_window
map ctrl+shift+f        move_window_forward
map ctrl+shift+b        move_window_backward
map ctrl+shift+`        move_window_to_top

map ctrl+shift+1        first_window
map ctrl+shift+2        second_window
map ctrl+shift+3        third_window
map ctrl+shift+4        fourth_window
map ctrl+shift+5        fifth_window
map ctrl+shift+6        sixth_window
map ctrl+shift+7        seventh_window
map ctrl+shift+8        eighth_window
map ctrl+shift+9        ninth_window
map ctrl+shift+0        tenth_window

map ctrl+l   next_tab
map ctrl+h     previous_tab
map ctrl+q        new_tab
map ctrl+w       close_tab
map ctrl+shift+.        move_tab_forward
map ctrl+shift+,        move_tab_backward

#################
#### OPACITY ####
#################

#background_opacity 0.8
#background_opacity 0.5
#background_opacity 0.65
background_opacity 0.750

#window terminal close question
confirm_os_window_close 0


# gaps  top right bottom left
window_padding_width 1 10 1 10

# Abrir Zellij con Ctrl+Q
#map ctrl+w send_text all \x1bzzellij --layout minimal\x0d


####################
#### FONT/ICONS ####
####################

font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font Bold
italic_font      FiraCode Nerd Font Italic
bold_italic_font FiraCode Nerd Font Bold Italic

font_size 10.0



########### TABS###########
tab_bar_style powerline
active_tab_foreground #ffffff
active_tab_background #005f87
inactive_tab_foreground #cccccc
inactive_tab_background #1c1c1c
#tab_powerline_style round
tab_bar_style fade

#################
#### THEMES #####
#################


include /home/cali/.config/kitty/kitty-themes/themes/Dracula.conf
#include /home/cali/.config/kitty/kitty-themes/themes/Atom.conf
