wallpaper {
    monitor = DP-1
    path = /home/cali/wallpapers/oversized-cat.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/cali/wallpapers/girl_red_ballons.jpg
    fit_mode = cover
}
